server:
  port: 3344

spring:
  application:
    name: cloud-config-center   #注册进eureka服务器的微服务名
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/config
#        git:
#          uri: git@gitgithub.com:zzyybs/springcloud-config.git   #GitHub上面的git仓库名字
          #搜索目标
          search-paths:
            - springcloud-config
      #####读取分支
      label: master

#服务注册到eureka地址
eureka:
  client:
    #表示是否将自己注册进eureka Server，默认为true
    register-with-eureka: true
    #是否从eureka Server抓取已有的注册信息，默认为true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:7001/eureka